import type { Metadata } from "next";
import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from '@/app/StoreProvider';
import Header from '@/components/Layout/Header';

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: [ "latin" ],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: [ "latin" ],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
	return (
		<html lang="en">
		<body className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }>
		<Header/>
		<StoreProvider>
			{ children }
		</StoreProvider>
		</body>
		</html>
	);
}
